#!/usr/bin/env bash
# ApiLens pull-request check, usable from any CI:
#   1. index the frontend
#   2. backend API changes base...working tree -> frontend impact   (api-changes.md)
#   3. changed frontend files -> checked against the new contract   (contract.md)
# Writes $APILENS_OUT/report.md (and the GitHub job summary when available).
# Exit code: 1 when either check fails at the configured level.
#
# Required: APILENS_FRONTEND, APILENS_BACKEND, APILENS_BASE (git ref, e.g. origin/main)
# Optional: APILENS_CLI (default: this repo's CLI), APILENS_INDEX, APILENS_OUT,
#           APILENS_FAIL_ON (definite|likely|possible|never, default definite),
#           APILENS_CHECK_FAIL_ON (error|warning|never, default error)
set -uo pipefail

: "${APILENS_FRONTEND:?set APILENS_FRONTEND to the frontend directory}"
: "${APILENS_BACKEND:?set APILENS_BACKEND to the backend directory}"
: "${APILENS_BASE:?set APILENS_BASE to the base git ref}"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
read -r -a cli <<< "${APILENS_CLI:-node $here/../packages/cli/dist/bin.js}"
out="${APILENS_OUT:-.apilens}"
index="${APILENS_INDEX:-$out/index.db}"
mkdir -p "$out"
apilens() { "${cli[@]}" --index "$index" "$@"; }

status=0
apilens index "$APILENS_FRONTEND" > /dev/null || exit 2

apilens diff --base "$APILENS_BASE" --backend "$APILENS_BACKEND" \
  --format markdown --fail-on "${APILENS_FAIL_ON:-definite}" --out "$out/api-changes.md" > /dev/null
code=$?
if [ "$code" -gt 1 ]; then exit "$code"; fi
status=$((status | code))

apilens extract-backend "$APILENS_BACKEND" > /dev/null || exit 2
apilens check --changed-since "$APILENS_BASE" \
  --format markdown --fail-on "${APILENS_CHECK_FAIL_ON:-error}" --out "$out/contract.md" > /dev/null
code=$?
if [ "$code" -gt 1 ]; then exit "$code"; fi
status=$((status | code))

{
  cat "$out/api-changes.md"
  printf '\n\n'
  cat "$out/contract.md"
  printf '\n\n<sub>Generated by ApiLens.</sub>\n'
} > "$out/report.md"
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then cat "$out/report.md" >> "$GITHUB_STEP_SUMMARY"; fi
echo "ApiLens report: $out/report.md"
exit "$status"
